@startuml
'https://plantuml.com/class-diagram

left to right direction
actor Bibliotecari
actor Usuari

rectangle "Plataforma Educativa"{
    usecase "Registrar nous llibres" as UC1
    usecase "Gestionar Prestec" as UC2
    usecase "Buscar Llibres" as UC3
    usecase "Prestec Llibres" as UC4
    usecase "Notificar Retard" as UC5
}

Bibliotecari --> UC1
Bibliotecari --> UC2
Usuari --> UC3
Usuari --> UC4
UC4 <.. UC5 : <<extend>>

@enduml