@startuml
'https://plantuml.com/class-diagram
' Sistema de Reserva d'Hotels:
' Volem fer el disseny de casos d'ús d'una aplicació de reserva d'habitacions d'hotel,
' on els clients poden cercar hotels, fer reserves i cancel·lar-les si és el cas.
' D'altra banda, els administradors d'hotel poden gestionar les reserves i afegir nous hotels.
' Important: quan una reserva s'apropa, cal enviar un recordatori de la reserva s'activa.

left to right direction
actor Client
actor Administrador

rectangle "Reserva al hotel"{
    usecase "Cercar hotels" as CH
    usecase "Reservar Hotel" as RH
    usecase "Cancelar Reserva" as CR
    usecase "Gestionar  Reserva" as GR
    usecase "Afegir Nou Hotel" as ANH
    usecase "Enviar Recordatori De Reserva" as ER
}

Client --> CH
Client --> RH
Client --> CR
Administrador --|> Client
Administrador --> GR
Administrador --> ANH
RH <.. ER : <<extend>>

@enduml