@startuml
'https://plantuml.com/class-diagram

left to right direction
actor Professor
actor Estudiante

rectangle "Plataforma Educativa"{
    usecase "Crear Curso" as UC1
    usecase "Gestinar Contigut" as UC2
    usecase "Inscribir al Curso" as UC3
    usecase "Validar Pagament" as UC4
}

Professor --> UC1
Professor --> UC2
Estudiante --> UC3
UC3 ..> UC4 : <<include>>
@enduml